 CREATE DATABASE IF NOT EXISTS CLIENTES_CRM;

 USE CLIENTES_CRM;

 CREATE TABLE CD_CLIENT_STATE 
 (STATE_TP_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) NOT NULL NULL,
 DESCRIPTION VARCHAR(100) NOT NULL NULL);

 CREATE TABLE CLIENT
 (CLIENT_ID INT AUTO_INCREMENT PRIMARY KEY,
 SINCE_DT DATE NOT NULL,
 LAST_UPDATE_DT DATE DEFAULT NULL,
 LAST_UPDATE_USER VARCHAR(20),
 CLIENT_STATE INT NOT NULL,
 INACTIVATED_DATE DATE DEFAULT NULL,
 CELLPHONE INT NOT NULL,
 EMAIL VARCHAR(60) DEFAULT NULL,
 ADDRESS VARCHAR(80) DEFAULT NULL,
 PERSON_ORG_CODE CHAR(1) NOT NULL,
 FOREIGN KEY (CLIENT_STATE) REFERENCES CD_CLIENT_STATE (STATE_TP_CD));

 CREATE TABLE CD_IDENTIFIER_TYPE
 (ID_TP_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) NOT NULL,
 DESCRIPTION VARCHAR(100) DEFAULT NULL);
 
 CREATE TABLE IDENTIFIER
 (IDENTIFIER_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 CLIENT_ID INT NOT NULL,
 ID_TYPE_CODE  INT NOT NULL,
 ID_NUMBER  INT NOT NULL,
 NIT_CHECK_NUMBER INT DEFAULT NULL,
 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID),
 FOREIGN KEY (ID_TYPE_CODE) REFERENCES CD_IDENTIFIER_TYPE (ID_TP_CD));
 
 CREATE TABLE CD_SEGMENT_TYPE
 (SEG_TP_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) NOT NULL);
 
 CREATE TABLE SEGMENT
 (SEGMENT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 CLIENT_ID INT NOT NULL,
 START_DT DATE NOT NULL,
 SEGMENT_TYPE_CODE INT NOT NULL,
 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID),
 FOREIGN KEY (SEGMENT_TYPE_CODE) REFERENCES CD_SEGMENT_TYPE (SEG_TP_CD));

  CREATE TABLE CD_CITY 
 (CITY_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL);
 
 CREATE TABLE CD_DEPARTMENT
 (DEPARTMENT_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL);

 CREATE TABLE CD_COUNTRY 
 (COUNTRY_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL,
 CAPITAL VARCHAR(60) DEFAULT NULL);
 
 CREATE TABLE CD_MARITAL_STATE 
 (MARITAL_ST_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL);

 CREATE TABLE CD_OCUPATION
 (OCUPATION_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL);

 CREATE TABLE CD_STUDY_LEVEL
 (STUDY_LVL_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL);
 
 CREATE TABLE FINANCIALS
 (FINANCIALS_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 CLIENT_ID INT NOT NULL,
 LAST_UPDT_DT DATE DEFAULT NULL,
 LAST_UPDT_USER VARCHAR(20) DEFAULT 'GENERALBATCH' ,
 START_DT DATE NOT NULL,
 LIABILITIES INT DEFAULT '0',
 ASSETS INT DEFAULT '0',
 EXPENSES INT DEFAULT '0',
 INCOME INT DEFAULT '0',
 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID));
 
 CREATE TABLE PERSON
 (CLIENT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 BIRTHDATE DATE NOT NULL,
 FIRST_NAME VARCHAR(20)NOT NULL,
 SECOND_NAME VARCHAR(20),
 LAST_NAME VARCHAR(20) NOT NULL,
 SECOND_LAST_NAME VARCHAR(20),
 BIRTH_CITY INT DEFAULT NULL,
 BIRTH_DEPARTMENT INT DEFAULT NULL,
 BIRTH_COUNTRY INT NOT NULL,
 MARITAL_STATE INT DEFAULT NULL,
 OCUPATION INT,
 GENDER CHAR(1) NOT NULL,
 STUDY_LEVEL INT DEFAULT NULL,
 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID),
 FOREIGN KEY (BIRTH_CITY) REFERENCES CD_CITY (CITY_CD),
 FOREIGN KEY (BIRTH_DEPARTMENT) REFERENCES CD_DEPARTMENT (DEPARTMENT_CD),
 FOREIGN KEY (BIRTH_COUNTRY) REFERENCES CD_COUNTRY (COUNTRY_CD),
 FOREIGN KEY (MARITAL_STATE) REFERENCES CD_MARITAL_STATE (MARITAL_ST_CD),
 FOREIGN KEY (OCUPATION) REFERENCES CD_OCUPATION (OCUPATION_CD),
 FOREIGN KEY (STUDY_LEVEL) REFERENCES CD_STUDY_LEVEL (STUDY_LVL_CD));
 
 CREATE TABLE CD_ORG_TYPE
 (ORG_TYPE_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) NOT NULL);
 
 CREATE TABLE CD_ECONOMIC_ACTIVITY
 (CIIU_CD INT NOT NULL PRIMARY KEY,
 DESCRIPTION VARCHAR(100) NOT NULL);
 
 CREATE TABLE ORG
 (CLIENT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 ESTABLISHED_DT DATE,
 ORG_NAME VARCHAR(80) NOT NULL,
 CONSTITUTION_CITY INT DEFAULT NULL,
 CONSTITUTION_COUNTRY INT NOT NULL,
 NUMBER_OF_EMPLOY INT DEFAULT NULL,
 ORG_TYPE INT NOT NULL,
 ECONOMIC_ACTIVITY INT NOT NULL,
 STOCK_INDICATOR BOOLEAN DEFAULT '0',
 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID),
 FOREIGN KEY (CONSTITUTION_CITY) REFERENCES CD_CITY (CITY_CD),
 FOREIGN KEY (CONSTITUTION_COUNTRY) REFERENCES CD_COUNTRY (COUNTRY_CD),
 FOREIGN KEY (ORG_TYPE) REFERENCES CD_ORG_TYPE (ORG_TYPE_CD),
 FOREIGN KEY (ECONOMIC_ACTIVITY) REFERENCES CD_ECONOMIC_ACTIVITY (CIIU_CD));
 
 CREATE TABLE CD_PRODUCT_TYPE
 (PRODUCT_TP_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL,
 DESCRIPTION VARCHAR(100) DEFAULT NULL);
 
 CREATE TABLE CD_INTEREST_RATE_TYPE
 (INT_RATE_TP_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) NOT NULL,
 ABBREVIATION VARCHAR(5) NOT NULL);
 
 CREATE TABLE CD_OFFICE
 (OPEN_OFFICE_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) NOT NULL,
 LOCATION VARCHAR(100) NOT NULL,
 OFFICE_STATE VARCHAR(10) DEFAULT 'Activo');
 
 CREATE TABLE PRODUCT
 (PRODUCT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 CLIENT_ID INT NOT NULL,
 PRODUCT_NUMBER INT NOT NULL,
 PRODUCT_OPEN_OFFICE INT DEFAULT NULL,
 CASH_VALUE DECIMAL(20,3) NOT NULL,
 INTEREST_RATE_TYPE INT NOT NULL,
 INTEREST_RATE DECIMAL(5,3) DEFAULT NULL,
 PRODUCT_STATUS VARCHAR(10) NOT NULL,
 PRODUCT_TYPE INT,
 PRODUCT_TERMINATION INT DEFAULT NULL,
 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID),
 FOREIGN KEY (PRODUCT_OPEN_OFFICE) REFERENCES CD_OFFICE (OPEN_OFFICE_CD),
 FOREIGN KEY (INTEREST_RATE_TYPE) REFERENCES CD_INTEREST_RATE_TYPE (INT_RATE_TP_CD),
 FOREIGN KEY (PRODUCT_TYPE) REFERENCES CD_PRODUCT_TYPE (PRODUCT_TP_CD));
 
 
 