 CREATE TABLE CD_CLIENT_STATE 
 (STATE_TP_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL,
 DESCRIPTION VARCHAR(100) DEFAULT NULL)

 CREATE TABLE CLIENT
 (CLIENT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 SINCE_DT DATE,
 LAST_UPDATE_DT DATE,
 LAST_UPDATE_USER VARCHAR(20),
 CLIENT_STATE INT,
 INACTIVATED_DATE DATE,
 CELLPHONE INT,
 EMAIL VARCHAR(60),
 ADDRESS VARCHAR(80),
 PERSON_ORG_CODE CHAR(1),
 FOREIGN KEY (CLIENT_STATE) REFERENCES CD_CLIENT_STATE (STATE_TP_CD))

 CREATE TABLE CD_IDENTIFIER_TYPE
 (ID_TP_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL,
 DESCRIPTION VARCHAR(100) DEFAULT NULL)
 
 CREATE TABLE IDENTIFIER
 (IDENTIFIER_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 CLIENT_ID INT,
 ID_TYPE_CODE INT,
 ID_NUMBER INT,
 NIT_CHECK_NUMBER INT,
 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID),
 FOREIGN KEY (ID_TYPE_CODE) REFERENCES CD_IDENTIFIER_TYPE (ID_TP_CD))
 
 CREATE TABLE CD_SEGMENT_TYPE
 (SEG_TP_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL,
 DESCRIPTION VARCHAR(100) DEFAULT NULL)
 
 CREATE TABLE SEGMENT
 (SEGMENT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 CLIENT_ID INT,
 START_DT DATE,
 SEGMENT_TYPE_CODE INT,
 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID),
 FOREIGN KEY (SEGMENT_TYPE_CODE) REFERENCES CD_SEGMENT_TYPE (SEG_TP_CD))

 CREATE TABLE CD_CITY 
 (CITY_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL)
 
 CREATE TABLE CD_DEPARTMENT
 (DEPARTMENT_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL)

 CREATE TABLE CD_COUNTRY 
 (COUNTRY_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL)
 
 CREATE TABLE CD_MARITAL_STATE 
 (MARITAL_ST_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL)

 CREATE TABLE CD_OCUPATION
 (OCUPATION_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL,
 DESCRIPTION VARCHAR(100) DEFAULT NULL)

 CREATE TABLE CD_STUDY_LEVEL
 (STUDY_LVL_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL,
 DESCRIPTION VARCHAR(100) DEFAULT NULL)
 
 CREATE TABLE FINANCIALS
 (FINANCIALS_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 CLIENT_ID INT,
 LAST_UPDT_DT DATE,
 LAST_UPDT_USER VARCHAR(20),
 START_DT DATE,
 LIABILITIES INT,
 ASSETS INT,
 EXPENSES INT,
 INCOME INT,
 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID))
 
 CREATE TABLE PERSON
 (CLIENT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 BIRTHDATE DATE,
 FIRST_NAME VARCHAR(20),
 SECOND_NAME VARCHAR(20),
 LAST_NAME VARCHAR(20),
 SECOND_LAST_NAME VARCHAR(20),
 BIRTH_CITY INT,
 BIRTH_DEPARTMENT INT,
 BIRTH_COUNTRY INT,
 MARITAL_STATE INT,
 OCUPATION INT,
 GENDER CHAR(1),
 STUDY_LEVEL INT,
 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID),
 FOREIGN KEY (BIRTH_CITY) REFERENCES CD_CITY (CITY_CD),
 FOREIGN KEY (BIRTH_DEPARTMENT) REFERENCES CD_DEPARTMENT (DEPARTMENT_CD),
 FOREIGN KEY (BIRTH_COUNTRY) REFERENCES CD_COUNTRY (COUNTRY_CD),
 FOREIGN KEY (MARITAL_STATE) REFERENCES CD_MARITAL_STATE (MARITAL_ST_CD),
 FOREIGN KEY (OCUPATION) REFERENCES CD_OCUPATION (OCUPATION_CD),
 FOREIGN KEY (STUDY_LEVEL) REFERENCES CD_STUDY_LEVEL (STUDY_LVL_CD))
 
 CREATE TABLE CD_ORG_TYPE
 (ORG_TYPE_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL,
 DESCRIPTION VARCHAR(100) DEFAULT NULL)
 
 CREATE TABLE CD_ECONOMIC_ACTIVITY
 (CIIU_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL,
 DESCRIPTION VARCHAR(100) DEFAULT NULL)
 
 CREATE TABLE ORG
 (CLIENT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 ESTABLISHED_DT DATE,
 ORG_NAME VARCHAR(80),
 CONSTITUTION_CITY INT,
 CONSTITUTION_COUNTRY INT,
 NUMBER_OF_EMPLOY INT,
 ORG_TYPE INT,
 ECONOMIC_ACTIVITY INT,
 STOCK_INDICATOR BOOLEAN,
 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID),
 FOREIGN KEY (CONSTITUTION_CITY) REFERENCES CD_CITY (CITY_CD),
 FOREIGN KEY (CONSTITUTION_COUNTRY) REFERENCES CD_COUNTRY (COUNTRY_CD),
 FOREIGN KEY (ORG_TYPE) REFERENCES CD_ORG_TYPE (ORG_TYPE_CD),
 FOREIGN KEY (ECONOMIC_ACTIVITY) REFERENCES CD_ECONOMIC_ACTIVITY (CIIU_CD))
 
 CREATE TABLE CD_PRODUCT_TYPE
 (PRODUCT_TP_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL,
 DESCRIPTION VARCHAR(100) DEFAULT NULL)
 
 CREATE TABLE CD_INTEREST_RATE_TYPE
 (INT_RATE_TP_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL,
 DESCRIPTION VARCHAR(100) DEFAULT NULL)
 
 CREATE TABLE CD_OFFICE
 (OPEN_OFFICE_CD INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(60) DEFAULT NULL,
 DESCRIPTION VARCHAR(100) DEFAULT NULL,
 OFFICE_STATE VARCHAR(10))
 
 CREATE TABLE PRODUCT
 (PRODUCT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 CLIENT_ID INT,
 PRODUCT_NUMBER INT,
 PRODUCT_OPEN_OFFICE INT,
 CASH_VALUE DECIMAL(20,3),
 INTEREST_RATE_TYPE INT,
 INTEREST_RATE DECIMAL(5,3),
 PRODUCT_STATUS VARCHAR(10),
 PRODUCT_TYPE INT,
 PRODUCT_TERMINATION INT,
 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID),
 FOREIGN KEY (PRODUCT_OPEN_OFFICE) REFERENCES CD_OFFICE (OPEN_OFFICE_CD),
 FOREIGN KEY (INTEREST_RATE_TYPE) REFERENCES CD_INTEREST_RATE_TYPE (INT_RATE_TP_CD),
 FOREIGN KEY (PRODUCT_TYPE) REFERENCES CD_PRODUCT_TYPE (PRODUCT_TP_CD));
 
 
 